name: Workflow_tp_memory    # Nom du workflow

on:
  push:
    branches:
      - develop    # Le workflow se déclenche sur un push vers la branche 'develop'

jobs:
  test-memory:
    runs-on: self-hosted

    steps:
    - name: Verif code
      uses: actions/checkout@v2

    - name: Verif fichier jpg
       run: echo "FONCTIONNE"
