name: Workflow # Nom du workflow

on:
  push:
    branches:
      - develop # Le workflow se déclenche sur un push vers la bran>
jobs:
  lint:                                      # Job appelé 'lint'
    runs-on: self-hosted                     # Le job s'exécute sur>
    steps:
    - name: Checkout repository              # Étape pour récupérer> 
      uses: actions/checkout@v2              # Utilise l'action 'ch>
    - name: Trouve_et_liste_PHP_files        # Étape pour trouver t>
      run: |
        find . -name "*.php" > php_files.txt # Trouve les fichiers >
    - name: Verif_syntax_PHP_files           # Étape pour vérifier >
      run: |
        while IFS= read -r file; do
          php -l "$file"                     # Exécute la commande >        
        done < php_files.txt
