name: Workflow_tp_memory    # Nom du workflow

on:
  push:
    branches:
      - develop    # Le workflow se déclenche sur un push vers la branche 'develop'

jobs:
  test-memory:
    runs-on: self-hosted

    steps:
    - name: Verif code
      uses: actions/checkout@v2

    - name: Verif fichier jpg
      run: |
        IMG_REPLACEMENT="/home/user/memory_lozano/img_st.jpg"    #cherche l'image de remplacement
        for file in $(find . -name '*.jpg'); do    #trouve et verifie les fich>           echo "Vérification de $file"
          if ! file "$file" | grep -q 'JPEG'; then
            echo "$file est corrompu. Remplacement..."
            cp "$IMG_REPLACEMENT" "$file"    #remplace si corrompu
          fi
        done

  build-memory:
    runs-on: self-hosted
    needs: test-memory

    steps:
    - name: Verif code
      uses: actions/checkout@v2

    - name: build img docker
      run: docker build -t lozan0/memory .
